-- ArcPay Link — initial PostgreSQL schema (Neon).
-- Generated by `prisma migrate diff` and extended with the two CHECK
-- invariants that Prisma's schema language cannot express. Managed by
-- `prisma migrate deploy`.

-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "public";

-- CreateTable
CREATE TABLE "payments" (
    "id" TEXT NOT NULL,
    "amount_usdc" TEXT NOT NULL,
    "amount_base_units" TEXT NOT NULL,
    "recipient" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "status" TEXT NOT NULL,
    "tx_hash" TEXT,
    "payer" TEXT,
    "failure_reason" TEXT,
    "created_at" TEXT NOT NULL,
    "confirmed_at" TEXT,

    CONSTRAINT "payments_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "tx_claims" (
    "tx_hash" TEXT NOT NULL,
    "payment_id" TEXT NOT NULL,
    "claimed_at" TEXT NOT NULL,

    CONSTRAINT "tx_claims_pkey" PRIMARY KEY ("tx_hash")
);

-- CreateIndex
CREATE UNIQUE INDEX "payments_tx_hash_key" ON "payments"("tx_hash");

-- CreateIndex
CREATE INDEX "payments_created_at_idx" ON "payments"("created_at");

-- CreateIndex
CREATE INDEX "tx_claims_payment_id_idx" ON "tx_claims"("payment_id");

-- ArcPay invariants (preserved from the verified SQLite schema).
--
-- 1. `payments_tx_hash_key` above is UNIQUE and nullable. PostgreSQL treats
--    NULLs as distinct in unique indexes, so many PENDING payments may hold
--    NULL while a non-null transaction hash can belong to at most one payment.
--    This is the PostgreSQL equivalent of the previous partial index
--    `CREATE UNIQUE INDEX ... ON payments(tx_hash) WHERE tx_hash IS NOT NULL`.
--
-- 2. A payment that is CONFIRMED must have a tx_hash, and any tx_hash implies
--    CONFIRMED. `tx_claims.tx_hash` (PRIMARY KEY) remains the atomic replay
--    guard used by the claim transaction.

-- AlterTable
ALTER TABLE "payments"
  ADD CONSTRAINT "payments_status_check"
  CHECK ("status" IN ('PENDING', 'CONFIRMED', 'EXPIRED'));

-- AlterTable
ALTER TABLE "payments"
  ADD CONSTRAINT "payments_confirmed_requires_tx_hash_check"
  CHECK (("status" = 'CONFIRMED') = ("tx_hash" IS NOT NULL));
